#!/usr/bin/env tclsh

# This file is part of MOO2 Launcher.
#
# Copyright (C) 2017-2020 MOO2 1.50 Project.
#
# This program is free software distributed under the
# terms of GNU GPL 2, see src/LAUNCHER.TXT for details.

source [file join [pwd] [file dirname [info script]] src main.tcl]
