#!/bin/bash
set -e
moo2_pack=$(s/make-moo2-package)
moo2_ver=${moo2_pack#MOO2.}
[ "$moo2_ver" != "" ] || (echo no version in package name: $moo2_pack; exit 1)
git_ver=$(git describe --dirty)
if [ "$la_ver" == "git" ]
then
    la_ver=-$git_ver
fi
out=MOO2-${moo2_ver}${la_ver}
[ -d "$out" ] && rm -rf "$out"
mkdir "$out"
cp -r src install-linux install-win32.exe misc/install.txt "$out"
cp install-linux "$out"/install-macosx
cp -r "$moo2_pack" "$out"/patch
cp LICENSE "$out"/src/GPL2.TXT
cp misc/dosbox.conf "$out/patch/150"
echo $git_ver > "$out/src/VERSION"
echo $out
zip=$out.zip
[ -f "$zip" ] && rm "$zip"
zip -qr "$zip" "$out"
echo "$zip"
